name: "w3security Gradle (jdk12)"
description: "Check your Gradle application for vulnerabilties using w3security"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which w3security command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to w3security"
  json:
    description: "Output a w3security.json file with results if running the test command"
    default: false
runs:
  using: "docker"
  image: "docker://w3security/w3security:gradle-jdk12"
  env:
    FORCE_COLOR: 2
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    W3SECURITY_INTEGRATION_VERSION: gradle-jdk12
  args:
  - w3security
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
