name: "w3security Infrastructure as Code"
description: "Check your Infrastructure as Code fields for issues using w3security"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which w3security command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to w3security"
  file:
    description: "File to test"
  json:
    description: "Output a w3security.json file with results if running the test command"
    default: false
  sarif:
    description: "Output a w3security.sarif file with results if running the test command"
    default: true
runs:
  using: "docker"
  image: "docker://w3security/w3security:alpine"
  env:
    W3SECURITY_INTEGRATION_NAME: GITHUB_ACTIONS
    W3SECURITY_INTEGRATION_VERSION: iac
  args:
  - w3security
  - iac
  - ${{ inputs.command }}
  - ${{ inputs.file }}
  - ${{ inputs.args }}
