name: "Generate doApply GitHub Actions"
on:
  push:
    branches:
      - main

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Render latest template
        run: |
          ruby build.rb
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COMMIT_MSG: |
            Generated new GitHub Actions templates
            skip-checks: true
        run: |
          # Hard-code user config
          git config user.email "alert@log4j.codes"
          git config user.name "gitadvisor"
          git config --get-regexp "user\.(name|email)"
          # Update origin with token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Checkout the branch so we can push back to it
          git checkout main
          git add .
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin main)
